/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    FlatpickrWrapper: typeof import('./components/FlatpickrWrapper.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./components/Snackbar.vue')['default']
    Table: typeof import('./components/Table.vue')['default']
    TaskCardModal: typeof import('./components/TaskCardModal.vue')['default']
    TaskEditModal: typeof import('./components/TaskEditModal.vue')['default']
    TasksTable: typeof import('./components/TasksTable.vue')['default']
  }
}
